apiVersion: v1
kind: Pod
metadata:
  name: nginx1 
  labels:
    name: nginx1
spec:
  containers:
  - name: nginx1
    image: registry.cloudclusters.io/cloudclusters/nginx:<BUILD_TAG>
    ports:
    - containerPort: 80
